CREATE TABLE clan (
                      clan_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      name varchar(30) NOT NULL,
                      gold int CHECK (gold >= 0)
);
CREATE TABLE player (
                        player_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        gold int DEFAULT 0,
                        username varchar(30) NOT NULL,
                        clan_id bigint REFERENCES clan(clan_id) ON DELETE SET NULL
);
CREATE TABLE quest (
                       quest_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       is_complete boolean DEFAULT false,
                       gold_reward int DEFAULT 0,
                       user_id bigint REFERENCES player(player_id) ON DELETE CASCADE
);
CREATE TABLE tracker (
                         tracker_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         reason_update VARCHAR(20) NOT NULL,
                         updated_clan_id bigint REFERENCES clan(clan_id) ON DELETE CASCADE,
                         updater_user_id bigint REFERENCES player(player_id) ON DELETE SET NULL,
                         completed_task_id bigint REFERENCES quest(quest_id) ON DELETE SET NULL,
                         update_time timestamp DEFAULT now(),
                         before_update_gold int NOT NULL,
                         after_update_gold int NOT NULL check (after_update_gold >= 0),
                         difference int NOT NULL
);
INSERT INTO clan(name, gold) VALUES('clan_test_name1', 10000);
INSERT INTO clan(name, gold) VALUES('clan_test_name2', 10500);
INSERT INTO clan(name, gold) VALUES('clan_test_name3', 11000);
INSERT INTO clan(name, gold) VALUES('clan_test_name4', 12000);

INSERT INTO quest(quest_id) VALUES(0);

INSERT INTO player(gold, username, clan_id) VALUES(500, 'test1', 1);
INSERT INTO player(gold, username, clan_id) VALUES(500, 'test2', 2);
INSERT INTO player(gold, username, clan_id) VALUES(500, 'test3', 3);
INSERT INTO player(gold, username, clan_id) VALUES(500, 'test4', 4);
INSERT INTO player(gold, username, clan_id) VALUES(500, 'test5', 1);
INSERT INTO player(gold, username, clan_id) VALUES(500, 'test6', 2);
INSERT INTO player(gold, username, clan_id) VALUES(500, 'test7', 3);
INSERT INTO player(gold, username, clan_id) VALUES(500, 'test8', 4);
INSERT INTO player(gold, username, clan_id) VALUES(500, 'test9', 1);
INSERT INTO player(gold, username, clan_id) VALUES(500, 'test10', 2);
INSERT INTO player(gold, username, clan_id) VALUES(500, 'test11', 3);
INSERT INTO player(gold, username, clan_id) VALUES(500, 'test12', 4);
INSERT INTO player(gold, username, clan_id) VALUES(500, 'test13', 1);
INSERT INTO player(gold, username, clan_id) VALUES(500, 'test14', 2);
INSERT INTO player(gold, username, clan_id) VALUES(500, 'test15', 3);
INSERT INTO player(gold, username, clan_id) VALUES(500, 'test16', 4);
INSERT INTO player(gold, username, clan_id) VALUES(500, 'test17', 1);
INSERT INTO player(gold, username, clan_id) VALUES(500, 'test18', 2);
INSERT INTO player(gold, username, clan_id) VALUES(500, 'test19', 3);
INSERT INTO player(gold, username, clan_id) VALUES(500, 'test20', 4);